Repository hmcts/juror-scheduler-execution, pull requests merged in 2024-01, with the labels that each got.

#23 Dependency update
  .github/workflows/ci.yml
  Dockerfile
  Jenkinsfile_CNP
  README.md
  build.gradle
  charts/juror-scheduler-execution/Chart.yaml
  charts/juror-scheduler-execution/values.yaml
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/juror/job/execution/Application.java
  src/smokeTest/java/uk/gov/hmcts/juror/demo/controllers/SampleSmokeTest.java
Labels: dependencies, ns:juror, rel:juror-scheduler-execution-pr-23, prd:juror

#21 Update Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: ns:juror, prd:juror, rel:juror-scheduler-execution-pr-21

#25 removed
  infrastructure/.terraform-version
  infrastructure/provider.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:juror, prd:juror, rel:juror-scheduler-execution-pr-25

#30 adjust helm values
  charts/juror-scheduler-execution/Chart.yaml
  charts/juror-scheduler-execution/values.demo.template.yaml
  charts/juror-scheduler-execution/values.dev.template.yaml
  charts/juror-scheduler-execution/values.stg.template.yaml
Labels: ns:juror, prd:juror, rel:juror-scheduler-execution-pr-30

#31 remove sync
  Jenkinsfile_CNP
Labels: ns:juror, prd:juror, rel:juror-scheduler-execution-pr-31
